import React from 'react'
import { Paper, TableContainer, Table, TableBody, TableHead, TableRow, IconButton, TableCell } from '@material-ui/core'
import CheckCircleIcon from '@material-ui/icons/CheckCircle'
import DeleteIcon from '@material-ui/icons/Delete'
import EditIcon from '@material-ui/icons/Edit'
import { makeStyles } from '@material-ui/styles'
import { TextInput } from '../UIkit/index'
import { useState } from 'react'
import { useCallback } from 'react'
import { Size } from './types'
import { useMemo } from 'react'
import { ShoppingCart } from '@material-ui/icons'